#!/usr/bin/env node
/**
 * Regenerates index.html and atlas.json from every explainers/<slug>/meta.json.
 * Never hand-edit index.html or atlas.json — this file owns them.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const EXPLAINERS = join(ROOT, "explainers");

const slugs = existsSync(EXPLAINERS)
  ? readdirSync(EXPLAINERS).filter((d) => statSync(join(EXPLAINERS, d)).isDirectory()).sort()
  : [];

const entries = slugs
  .filter((s) => existsSync(join(EXPLAINERS, s, "meta.json")))
  .map((s) => JSON.parse(readFileSync(join(EXPLAINERS, s, "meta.json"), "utf8")));

const esc = (s) => String(s).replace(/[&<>"']/g, (c) =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

/* ------------------------------------------------------------- atlas.json */

const byDomain = {};
for (const e of entries) (byDomain[e.domain] ??= []).push(e.slug);
const patterns = {};
for (const e of entries) patterns[e.interaction_pattern] = (patterns[e.interaction_pattern] ?? 0) + 1;

writeFileSync(join(ROOT, "atlas.json"), JSON.stringify({
  generated_at: new Date().toISOString().slice(0, 10),
  count: entries.length,
  domains: Object.fromEntries(Object.entries(byDomain).sort()),
  interaction_patterns: Object.fromEntries(Object.entries(patterns).sort()),
  explainers: entries.sort((a, b) => a.slug.localeCompare(b.slug)),
}, null, 2) + "\n");

/* ------------------------------------------------------------- index.html */

const domains = Object.keys(byDomain).sort();
const sections = domains.map((d) => {
  const cards = entries
    .filter((e) => e.domain === d)
    .sort((a, b) => a.difficulty - b.difficulty || a.title.localeCompare(b.title))
    .map((e) => `        <li class="card">
          <a href="explainers/${esc(e.slug)}/index.html">
            <h3>${esc(e.title)}</h3>
            <p>${esc(e.summary)}</p>
          </a>
          <p class="meta"><span class="diff" aria-label="difficulty ${e.difficulty} of 5">${"●".repeat(e.difficulty)}${"○".repeat(5 - e.difficulty)}</span> <span>${esc(e.interaction_pattern)}</span> <span>${e.assertions_count} checks</span></p>
        </li>`).join("\n");
  return `      <section aria-labelledby="d-${esc(d)}">
        <h2 id="d-${esc(d)}">${esc(d.replace(/-/g, " "))}</h2>
        <ul class="grid">
${cards}
        </ul>
      </section>`;
}).join("\n");

writeFileSync(join(ROOT, "index.html"), `<!doctype html>
<!-- GENERATED by tools/build_index.mjs — do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Interactive Explainer Atlas</title>
<meta name="description" content="A growing collection of self-contained interactive explainers, one concept per page.">
<style>
:root{--bg:#fbfaf8;--panel:#fff;--ink:#15181d;--muted:#5a6270;--line:#e2e0da;--accent:#2f6f4f;--radius:10px}
@media (prefers-color-scheme:dark){:root{--bg:#101317;--panel:#171b21;--ink:#e8eaed;--muted:#9aa3b0;--line:#272d36;--accent:#63c08e}}
*{box-sizing:border-box}html{color-scheme:light dark}
body{margin:0;background:var(--bg);color:var(--ink);font:1rem/1.6 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
.wrap{max-width:68rem;margin:0 auto;padding:clamp(16px,4vw,40px)}
h1{font-size:clamp(1.7rem,1.2rem+2.2vw,2.6rem);margin:0 0 .25em;letter-spacing:-.015em}
.lede{color:var(--muted);max-width:42em;margin:0 0 .6em}
.count{font:600 .8rem/1 ui-monospace,monospace;color:var(--accent)}
h2{font-size:1.05rem;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);margin:2.4em 0 .8em;border-bottom:1px solid var(--line);padding-bottom:.4em}
.grid{list-style:none;margin:0;padding:0;display:grid;gap:14px;grid-template-columns:repeat(auto-fill,minmax(min(100%,17rem),1fr))}
.card{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);padding:16px;display:flex;flex-direction:column;gap:.5em}
.card a{text-decoration:none;color:inherit}
.card a:hover h3{color:var(--accent)}
.card a:focus-visible{outline:2.5px solid var(--accent);outline-offset:3px;border-radius:6px}
.card h3{margin:0 0 .3em;font-size:1.04rem;line-height:1.3}
.card p{margin:0;color:var(--muted);font-size:.9rem}
.card .meta{display:flex;flex-wrap:wrap;gap:.7em;margin-top:auto;padding-top:.5em;font:.75rem/1 ui-monospace,monospace;color:var(--muted)}
.diff{color:var(--accent);letter-spacing:.1em}
.empty{color:var(--muted);font-style:italic}
footer{margin-top:3em;padding-top:1.2em;border-top:1px solid var(--line);color:var(--muted);font-size:.85rem}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>Interactive Explainer Atlas</h1>
    <p class="lede">One concept per page. Each page teaches a single idea through a working
    simulation you can take apart — every model on this site is checked numerically against
    closed forms, conservation laws, or published reference values before it ships.</p>
    <p class="count">${entries.length} explainer${entries.length === 1 ? "" : "s"} · ${domains.length} domain${domains.length === 1 ? "" : "s"} · ${entries.reduce((n, e) => n + e.assertions_count, 0)} assertions</p>
  </header>
  <main>
${sections || '      <p class="empty">No explainers yet.</p>'}
  </main>
  <footer><p>Every page is self-contained: no frameworks, no CDN, no network. Save one and it still works offline.</p></footer>
</div>
</body>
</html>
`);

console.log(`index.html + atlas.json rebuilt — ${entries.length} explainers across ${domains.length} domains`);
